site_name: Balanceamento - 2017 - 1S
pages:
- Home: 'index.md'
- Aulas :
  - 'Jogos e equilíbrio' : 'aulas/jogos-e-equilibrio.md'
  - 'Jogos como sistemas' : 'aulas/jogos-e-sistemas.md'
  - Polimento : 'aulas/polimento.md'
- Referências : 'referencias.md'
theme: bootstrap
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
markdown_extensions:
  - smarty
  - sane_lists